name: kpss_tarih_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_mobile_ads: ^5.3.1
  in_app_purchase: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.1 # <-- YENİ PAKET BURAYA EKLENDİ
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_launcher_icons: "^0.13.1" # Bu satırı ekleyin
  connectivity_plus: ^6.0.3 # İnternet bağlantısı kontrolü için eklendi



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/content/
    - assets/kpss_content.json
    - assets/random_questions.json
    - assets/kpss_tarih_tips.json
    - assets/icon/app_icon.png


flutter_launcher_icons:
  android: "launcher_icon" # Android için özel bir isim kullanmak isterseniz (isteğe bağlı)
  ios: false # iOS için simge oluşturulmasını sağlar
  image_path: "assets/icon/app_icon.png" # Buraya simge dosyanızın yolunu yazın
  min_sdk_android: 21 # Uygulamanızın desteklediği minimum Android SDK sürümü (genellikle 21 veya üzeri)



